#!/usr/bin/env ruby

require 'active_support'
require 'active_support/core_ext'

def library_file
  ARGV[0]
end

parameters = Array.new(ARGV)
parameters.shift

class Library

  def initialize(name, &block)
    instance_eval &block
  end

  def action(action_name, &block)
    (class << self; self; end).send(:define_method, action_name, &block)
  end

end



@libraries = {}

def library(name, &block)
  @libraries[name] = Library.new(name, &block)
end




load(library_file)

library_name = File.basename(library_file, '.rb')

@libraries[library_name.camelize.to_sym].send(*parameters)
